### ISSUE TITLE
Failed Attempt to add Components

### ISSUE THREAD

**Issue by DavZim** [DavZim/reactflow#2]
Following up on the earlier issue ([reactR/#93](https://github.com/react-R/reactR/issues/93) as well as PR #1 on this repo).

I am now trying to add different types to `reactflow`, such as `MiniMap`, `Controls`, and `Background`, but also styles and values passed to the components. (see [official documentation](https://reactflow.dev/components) and their [API reference](https://reactflow.dev/api-reference/components) for background...)

Following the documentation of ReactFlow, this is what the solution in pure React code would look like:

```js
<ReactFlow
  nodes={nodes}
  edges={edges}
>
  <Controls />
  <MiniMap />
  <Background variant="dots" gap={12} size={2} />
</ReactFlow>
```

I want the user to be able to pass Control, Background, MiniMap including options from R.

### Hardcoded values

When I run the code below (current version of [`srcjs/Reactflow.js`](https://github.com/DavZim/reactflow/blob/master/srcjs/ReactFlow.js)) with hard-coded components and styles, it works fine.

```js
// srcjs/Reactflow.js
import {
  ReactFlow as ReactFlowOrig, // Note this is renamed here...
  useNodesState,
  useEdgesState,
  addEdge,
  MiniMap,
  Controls,
  Background,
} from '@xyflow/react';

// ...
export default function ReactFlow({
  nodes,
  edges,
  ...props
}) {

  // ...
  return (
    <div style={{ width: '100vw', height: '100vh' }}>
      <ReactFlowOrig
        nodes={nodes}
        edges={edges},
        {...props}
      >
        // Note these values are hard-coded at the moment, but should be passed from R
        <Controls />
        <MiniMap />
        <Background variant="dots" gap={12} size={1} />
      </ReactFlowOrig>
    </div>
  );
}
```

From R I can then call the component like this:

```R
nodes <- list(
  list(id = "1", position = list(x = 0, y = 0), data = list(label = "1")),
  list(id = "2", position = list(x = 50, y = 100), data = list(label = "2")),
  list(id = "3", position = list(x = 100, y = 200), data = list(label = "3"))
)
edges <- list(
  list(id = "e1-2", source = "1", target = "2", type = "straight"),
  list(id = "e2-3", source = "2", target = "3", type = "smoothstep", label = "A", 
       animated = TRUE),
  list(id = "e1-3", source = "1", target = "3", type = "bezier")
)
reactflow::reactflow(
  nodes = nodes,
  edges = edges
)
```

this works, but in the end, the user cannot change controls, minimap, background, etc.
Instead. I want to be able to pass the components like this:
 
```R
reactflow::reactflow(
  nodes = nodes,
  edges = edges,
  controls(), #< added
  miniMap(), #< added
  background(variant = "dots", gap = 12, size = 2) #< added
)
```

which would change `srcjs/ReactFlow.js` to something like this (note this is a failed attempt, just wanted to highlight an attempt at a solution)

```js
// ...
export default function ReactFlow({
  nodes,
  edges,
  controls, //< added
  background, //< added
  miniMap, //< added
  ...props
}) {
  // ...
  return (
    <ReactFlowOrig
      nodes={final_nodes}
      edges={final_edges}
      // ...
      {...props}
    >
      {miniMap}, //< added
      {controls}, //< added
      {background} //< added
    </ReactFlowOrig>
  )
}
```

but this results in a js error: `react-tools.js:1 Uncaught Error: Unknown component: Controls`.
Also, it would be great if the three example components could be passed in ...props or so, so that other components can be passed on as well.

Note that I already have the functions `controls()`, `minimap()`, and `background()` in R ([`R/reactflow.R`](https://github.com/DavZim/reactflow/blob/master/R/reactflow.R)), which means, the following is working on its own:

```R
reactflow::miniMap()
#> <MiniMap></MiniMap>
reactflow::controls()
#> <Controls></Controls>
reactflow::background(variant = "dots", gap = 12, size = 21)
#> <Background variant="dots" gap="12" size="2"></Background>
```

Note that gap and size are not `gap={12} size={2}`, but `gap="12" size="2"` not sure if this will become a problem later on.

**Comment by DavZim** [comment]
@timelyportfolio, sorry to bother you again.
If you have time, I would be very grateful if you can provide me with your thoughts about this and maybe a solution or context to where I can find a solution to this.

I would be happy to contribute a Vignette to react-R of my learnings once I'm finished with a v1 of this package.

**Comment by timelyportfolio** [comment]
@DavZim no bother at all and excited you are working on this.  I submitted a pull that should add `components` as desired.  I did not check arguments to `background` but will later.

**Comment by DavZim** [comment]
@timelyportfolio wonderful, that solves it!
I will add some syntactic sugar so that it's easier to use. Also the arguments to background work out of the box 🥳 

Btw, should I include you as a contributor to DESCRIPTION? I feel its well deserved by now!
There are a couple of smaller open todos, but eventually the package should find its way to CRAN.

If you are up for another challenge: #3. (graph doesnt get redrawn in a shiny app on changes to its inputs)... 😄
